onlyBuiltDependencies:
  - '@firebase/util'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@vercel/speed-insights'
  - esbuild
  - msw
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
